### ISSUE TITLE
Always allow "Restart" menu item

### ISSUE THREAD

**Issue by unwiredben** [FauxFaux/PuTTYTray#107]
I'm frequently working on embedded systems where I need to reboot devices that I'm connected to over SSH.  A big annoyance is that PuTTY doesn't show the "Restart Connection" command until it detects that the connection has broken, something that often takes a timeout or trying to send new characters, then dismiss a dialog.  I'd like the ability to just manually restart a connection without having to wait for that condition.  Duplicate isn't sufficient, because that loses the current window's history and settings.

**Comment by nyuszika7h** [comment]
@FauxFaux This is broken in p0.64-t023. "Restart Session" does not show up until it detects that the connection has broken. Perhaps it's because of [this](https://github.com/FauxFaux/PuTTYTray/commit/a7c6cd79067f687f989c3204afdcc1c03e27ddc2#diff-88776592a9f52e2b3f2939253efbc5ecL383)?

**Comment by nyuszika7h** [comment]
@FauxFaux Any news on this? Still the same in p0.65-t025.

**Comment by FauxFaux** [comment]
Good spot, @nyuszika7h.  Fixed again!
