### ISSUE TITLE
Suggest: Write reconnection attempts to dialog box or title bar rather than to main screen...

### ISSUE THREAD

**Issue by puterboy** [FauxFaux/PuTTYTray#119]
One nice thing about the original PuTTY disconnection is that even after a disconnect one can still read the inactive screen for the last screenfull of content -- which is frequently useful... especially if there has been a crash...

With reconnection turned on, the reconnect attempts scroll over the last screen, wiping away the useful information and just replacing it with a scrolling list of failed attempts.

I think it would be better to write the reconnection attempts to a separate dialog box (or to signal it in the title bar with some type of icon...). Then only rewrite the screen when the reconnection attempt succeeds.

Actually, writing to a dialog box would be nice because then one could add the options to pause/resume connection attempts. For example, suppose I know I am going to be away from a network connection for an  extended period. Then I might want to temporarily disable the attempts until I get back to my network connection at which point I would want to resume the auto-reconnect functionality. I might have the following buttons: Pause/Resume and Cancel (or Close) where Cancel would close the connection entirely.

Note I am running the 2013-10-30 snapshot

**Comment by FauxFaux** [comment]
Reconnection is gone, so the nasty messages are gone too.
