### ISSUE TITLE
VS2013 project files: not loading common controls

### ISSUE THREAD

**Issue by FauxFaux** [FauxFaux/PuTTYTray#147]
i.e. ugly-ass crap in the debugger.

The putty.rc is there, and the flags are probably right.

**Comment by mmozeiko** [comment]
For me this occurred when VS2013 had enabled it's own manifest embedding. So putty manifest that enabled proper common control manifest was not used. So I disabled default manifest: Project Properties -> Linker -> Manifest File -> Generate Manifest = NO. After that proper common controls were loaded and putty was pretty again.

**Comment by FauxFaux** [comment]
VS2013 is comically long gone. Viva la VS2017!
