### ISSUE TITLE
Cygwin64 crashes cygterm

### ISSUE THREAD

**Issue by AeliusSaionji** [FauxFaux/PuTTYTray#166]
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: putty.exe
  Application Version:  0.63.20.0
  Application Timestamp:    52b6c608
  Fault Module Name:    putty.exe
  Fault Module Version: 0.63.20.0
  Fault Module Timestamp:   52b6c608
  Exception Code:   c0000005
  Exception Offset: 00068c8e
  OS Version:   6.3.9600.2.0.0.256.103
  Locale ID:    1033
  Additional Information 1: 5861
  Additional Information 2: 5861822e1919d7c014bbb064c64908b2
  Additional Information 3: d1d9
  Additional Information 4: d1d94a13d3609d6b740644c12508f581

**Comment by FauxFaux** [comment]
cygwin support is gone, sorry.
