### ISSUE TITLE
build 22 serial now broken

### ISSUE THREAD

**Issue by NAW77** [FauxFaux/PuTTYTray#174]
if i try and open a connection to my com3 port with the latest build 22 it return (null).
using the previous build and master before the latest changes work to the same com port 3 with no issue.

**Comment by renini** [comment]
i have the same issue, will this be fixed?

**Comment by NAW77** [comment]
Just to let you know the serial (NULL) issue still exists for the 0.64 merge branch.

**Comment by renini** [comment]
Yes please fix this...

**Comment by sizer99** [comment]
I did an unofficial build with NAW77's patch, VS2010++ 32-bit Release version.  Verified RS-232 is working, SSH is still working, Adb is /probably/ working (not getting the error) but I don't have that to test with.

https://www.dropbox.com/s/399wk33z5p86pxg/putty_unofficial_GH-174_fix.zip?dl=0

sha256 sum is 687b051bcbf9df729daeb38f98ae6aa039596100824b245822ba3adea38b5f6d

**Comment by Borkason** [comment]
Still not fixed?

**Comment by ColdIce1** [comment]
I also have this issue!

**Comment by FauxFaux** [comment]
Autoreconnect was removed in a7c6cd7, which is in p0.65-t025 (the latest release), which should fix this problem.  I have confirmed that telnet is working, and that serial at least doesn't just exit like it does in t023.
