### ISSUE TITLE
0.63-t022 has broken hyperlinks matching

### ISSUE THREAD

**Issue by wilkowy** [FauxFaux/PuTTYTray#182]
It looks like fixing bug #163 broke TLD matching. The custom regex is missing the last component "|[a-zA-Z][a-zA-Z]" matching any 2-char domains (national domains). However it seems that "Select sensible URLs" does use different (internal) broken regex. The only solution for now is to switch to "Select nearly any URLs" or fixing (by adding the missing part) & using custom regex.

**Comment by juj** [comment]
I'm seeing all URLs to `.fi` and `.se` addresses being broken, I believe this bug report describes the same issue?

See for an example:

![broken_se_and_fi](https://cloud.githubusercontent.com/assets/225351/6203720/403db008-b538-11e4-867c-15fe68cff5f6.png)

**Comment by saivert** [comment]
Also URL matching will match e.g timestamps in irc clients too if the url extend all the way out to the end of the buffer/window as it thinks the URL wraps to the next line which it doesn't.
Not sure if this can ever be solved though. Terminals really suck.

**Comment by FauxFaux** [comment]
This was fixed sometime in the abyss.
