### ISSUE TITLE
unexpected exiting while network interruption

### ISSUE THREAD

**Issue by jsjain007** [FauxFaux/PuTTYTray#187]
since our college has cyberoam implementation and i use it to bypass it since we have a daily download  limit so as soon as my id gets over and i enter a new id but it does not reconnects but instead after sometime  it closes automatically and yes i have  selected both options of attempt reconnect and attempt reconnect after computer sleep .
please help .

**Comment by FauxFaux** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEconnect is gone, woo.
