### ISSUE TITLE
PuTTY 0.64 released, fixing a security hole

### ISSUE THREAD

**Issue by arcanis** [FauxFaux/PuTTYTray#188]
Not sure if PuTTYTray is affected or not:
http://www.chiark.greenend.org.uk/~sgtatham/putty/

**Comment by jfhenriques** [comment]
really would like to knoe this too

**Comment by jkesanen** [comment]
PuTTYTray's ssh.c seems like missing this:

http://tartarus.org/~simon-git/gitweb/?p=putty.git;a=blobdiff;f=ssh.c;h=6009e06f0d3ec21e7a4fe6c9d1002f2e4da02502;hp=a7f5882f7dff2f87319578f8c559a884174e53cc;hb=174476813f0ed94337aecc3e2d13a202a1dc2fa8;hpb=db9385b3ce08c211c3e2b950aa1a0f656ba3ab01

**Comment by so0k** [comment]
Is there a pull request yet to apply the patch to puttytray?

**Comment by jkesanen** [comment]
so0k: https://github.com/FauxFaux/PuTTYTray/issues?q=is%3Aclosed+is%3Aissue

No.

**Comment by twpol** [comment]
I think @FauxFaux has merged 0.64 into PuTTYTray in https://github.com/FauxFaux/PuTTYTray/tree/merge but needs to fix some compiler issues and then test the changes to ensure everything is working together well.

**Comment by jkesanen** [comment]
Yes, you are right. 0.64 was merged some hours after my original comment.

https://github.com/FauxFaux/PuTTYTray/commit/22244d4f3f382954e6e4de7f373563ecc62f1df6#diff-5bfa45f3fb322e569a8101399c9c551c

Now ssh.c has this dh_validate_f() call that fixes the issue.

**Comment by NAW77** [comment]
The merge of 0.64 compiled and ran ok.  However #174 still not fixed unless I mod it to fix serial NULL!

**Comment by arcanis** [comment]
Then I guess this issue can be closed
