### ISSUE TITLE
Support for EC-Keys

### ISSUE THREAD

**Issue by SkateScout** [FauxFaux/PuTTYTray#195]
Hi,
is there an plan when the support for EC-Keys from the development version is included ?

**Comment by nyuszika7h** [comment]
ECDSA is already supported, see #139. You might have to use this version: https://github.com/fauxfaux/puttytray/issues/185#issuecomment-92013895

**Comment by SkateScout** [comment]
OK it was my fault i used the alpha Version from official putty and gernerated ED25519.
And thought that the support for ECDSA was missing to. Thanks for the hint.
