### ISSUE TITLE
Add support for ed25519 keys

### ISSUE THREAD

**Issue by nyuszika7h** [FauxFaux/PuTTYTray#196]
It would be nice if you could support ed25519 keys.

**Comment by tstaylor7** [comment]
I don't know how much your source has diverged from Simon Tatham's, but there it appears to have been implemented by a series of commits by [Chris Staite](http://tartarus.org/~simon-git/gitweb/?p=putty.git;a=search;s=Chris+Staite;st=author) on 2015-05-09.

**Comment by MoonUnit2** [comment]
Just found this request after trying to convert some new keys with PuttyTray. Ended up having to fall back to regular Putty in get the keys generated and then couldn't load them, and I guess this is why.

**Comment by ksteckert** [comment]
I concur.  I have to use regular Putty again since Puttytray doesn't support ED25519.  Please port over the new features from putty 0.69.  Thanks.

**Comment by FauxFaux** [comment]
This looks to have been fixed upstream, properly.

https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/ed25519.html
