### ISSUE TITLE
Latest Vista update KB3057839 makes PuTTY(Tray) windows invisible

### ISSUE THREAD

**Issue by casper** [FauxFaux/PuTTYTray#200]
See here:
http://superuser.com/questions/927268/cant-see-putty-window-on-windows-vista-any-longer

This issue has been fixed in mainline PuTTY 0.65:
http://superuser.com/a/932720/89010

Is it possible to integrated the fix into PuTTYTray also?

**Comment by casper** [comment]
http://tartarus.org/~simon-git/gitweb/?p=putty.git;a=commitdiff;h=be9e5ea0a05782df2aa455853d6e1e2efe4772b8

**Comment by FauxFaux** [comment]
This commit is included in p0.65-t025, so hopefully this will be fixed.  I haven't tested it, however.  Please test it and tell us what the status is!

**Comment by casper** [comment]
Works now on Vista. Thanks!
