### ISSUE TITLE
Support ssh:// URI

### ISSUE THREAD

**Issue by szepeviktor** [FauxFaux/PuTTYTray#203]
Please consider supporting `ssh://hostname:port` links. Maybe for other protocols too.

Article http://schipka.com/archives/34
and patch: http://schipka.com/wp-content/uploads/2008/09/putty_ssh.zip

**Comment by FauxFaux** [comment]
I've applied, updated and fixed some bugs in Schipka's patch, and it will be in the next release.

There's `.reg` files to include the protocol handlers with Windows, if that's what people want.  I haven't reviewed these:
https://b.goeswhere.com/putty-protocol-handler.reg.txt
https://b.goeswhere.com/putty-protocol-handler-remove.reg.txt

There was no licensing information included in the zip and I haven't contacted Schipka.  I'm claiming fair-use as the change is relatively small (especially after needing to be fixed to be the same as the `telnet:` code it copied).

**Comment by szepeviktor** [comment]
Thank you very much.
