### ISSUE TITLE
error: Hm, kex protocol error: type 30 seq 1 [preauth]

### ISSUE THREAD

**Issue by karametro** [FauxFaux/PuTTYTray#207]
Hi!

When trying to connect via ssh to a fedora 4.0.8-300.fc22.i686 nothing happens. 

It seems that ssh versión is: "SSH-2.0-OpenSSH_6.9"

Searching the sshd log, I see: 

error: Hm, kex protocol error: type 30 seq 1 [preauth]
Connection closed by x.x.x.x [preauth]

I have seen that similar happens with kitty: 

http://www.9bis.net/kitty/?action=forum&id=0617

Any help?

Thanks in advance.

**Comment by DataBeaver** [comment]
As a workaround, go to Connection -> SSH -> Kex and move "Diffie-Hellman group exchange" down below the line.

**Comment by FauxFaux** [comment]
0.65-p025 can connect to a 1:6.9p1-2 (Debian testing) server with the default configuration.

If you have any other examples of servers that can't be connected to, please re-open the issue.
