### ISSUE TITLE
Terminal Type String: from 'xterm' to 'putty'

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FauxFaux/PuTTYTray#208]
Is it possible to make the default putty Terminal Type String value from `xterm` to `putty`?

This makes zsh working with Home and End buttons but not only. It unlocks a series of non working buttons using by default xterm ( see https://github.com/robbyrussell/oh-my-zsh/issues/3757 ).

![photo323343160181893470](https://cloud.githubusercontent.com/assets/1237070/9111624/1d07ccc0-3c49-11e5-9d6e-7ca603d08aa0.jpg)

Thank you in advance!

P.S.: see this link for more detailed info: http://superuser.com/a/104016

**Comment by Reiner030** [comment]
Quick Solution:
=> set your parameters as wanted, goto "Session", select "Default Settings" and "Save" your changes ;)

**Comment by julianxhokaxhiu** [comment]
I know, I did it already. It's just a suggestion...

**Comment by nyuszika7h** [comment]
The problem with this is that if you **don't** have `ncurses-term` installed, things will break because of an invalid `TERM` value.

**Comment by julianxhokaxhiu** [comment]
Ah ok, understood. Then it's fine like this, at least can be configured :)
