### ISSUE TITLE
Can you please update the main website with the latest version

### ISSUE THREAD

**Issue by renini** [FauxFaux/PuTTYTray#209]
Can you please update the main website with the latest version?

SSH-2.0-OpenSSH_6.9p1 is getting more and more common.
Which does work with https://puttytray.goeswhere.com/download/v023/putty.exe

Also i think the serial com bug was fixed in that one also right?

**Comment by FauxFaux** [comment]
I have made a 0.65-based release the primary release, without extensive testing.  Let's see what happens!
