### ISSUE TITLE
Building guide for PuttyTray

### ISSUE THREAD

**Issue by antinucleon** [FauxFaux/PuTTYTray#211]
Is there any step by step guide for building PuttyTray? Old one doesn't work and I tried ```build-release.bat``` but no luck to get it work

**Comment by FauxFaux** [comment]
PuTTYTray can now be built exactly like upstream PuTTY.  However, there's also not a building guide for upstream PuTTY.  SIGH.

I've written one up:
https://github.com/FauxFaux/PuTTYTray/wiki/Building-with-VS2015-Community
