### ISSUE TITLE
Recconnect feature is not work in 0.65-t026 BETA

### ISSUE THREAD

**Issue by zdm** [FauxFaux/PuTTYTray#214]
Putty doesn't reconnecting automatically, like it does in previous version.
Just stuck with "reconnecting ...." message.

**Comment by SkateScout** [comment]
I use Windows 10 and think have the same problem since W10 if often crash and windows ask to Close or Debug. Are there any thinks to i can provide to fix the issue?

**Comment by zdm** [comment]
All versions after p0.63-t022 are not reconnected.

**Comment by galapogos01** [comment]
This is a recurrence of https://github.com/FauxFaux/PuTTYTray/issues/28

0.65-t026 has lost the delay widget, meaning all my sessions won't reconnect on wake.  Please put it back!

**Comment by DynamoEffects** [comment]
Confirming that the reconnect feature is broken on Win7 SP1 as well using 0.65-t026.  I have reverted back to p063-t022 for the time being.

**Comment by marcosdiez** [comment]
Same issue here. Windows 10 + 0.65-t026, it is broken :(

**Comment by Jcpetrucci** [comment]
:( This was one of the best features when it worked.

**Comment by cpainchaud** [comment]
+1 !

**Comment by ABLomas** [comment]
Even worse, you can't reconnect immediately - session hangs on password prompt. You must wait some time before reconnecting, because all reconnected sessions would hang for a minute or so...

**Comment by zdm** [comment]
Seems, that puttytray is dying without support.
This was my favorite ssh client for many years.
I can recommend kitty - all the same features, but without bugs and always synchronized with the latest putty release.

**Comment by SkateScout** [comment]
Hi, i looked ad Kitty there is one important issue missing ADB connection
handling.
And one nice to have and button to start the agent from the GUI.

An hint for the GUI would be use 2 rows for the bottom and make the
kategroy tree longer.
<open> <start>
<cancel> <About>
<Update> <Agent>


2015-12-16 21:44 GMT+01:00 zdm <notifications@github.com>:

**Comment by galapogos01** [comment]
Chris is actively working on PuttyTray - there have been commits this year already, and there was a version released in December (which still has this problem).

How do we get his attention on this issue?

**Comment by tibu** [comment]
I see that reconnect is unsupported. Do we know why?

**Comment by FauxFaux** [comment]
I'm dropping support for the re-connection code, properly this time.
