### ISSUE TITLE
putty.exe of p0.65-t026

### ISSUE THREAD

**Issue by szepeviktor** [FauxFaux/PuTTYTray#217]
Could we have a binary for p0.65-t026?

**Comment by szepeviktor** [comment]
Is there a CI for Windows (for example from Microsoft) that could compile PuTTYTray and upload it here?

**Comment by szepeviktor** [comment]
http://www.appveyor.com/ is free for open-source

**Comment by szepeviktor** [comment]
Is it only on the website?
https://puttytray.goeswhere.com/download/putty.exe

**Comment by FauxFaux** [comment]
I don't understand the question.

Is there something wrong with the binary on the website?  Do you want to build it yourself?

**Comment by szepeviktor** [comment]
Excuse for the first time I was only looking in GitHub releases then I've found it on the website.

**Comment by szepeviktor** [comment]
If there are test then please consider http://www.appveyor.com/

**Comment by FauxFaux** [comment]
There are no tests; upstream doesn't have any and I haven't added any.

I've added a note to the release notes to update Github Releases, if that's where people look.  I didn't do that for the previous release, which was Bad.
