### ISSUE TITLE
Please try to build cthelper with putty

### ISSUE THREAD

**Issue by kusuriya** [FauxFaux/PuTTYTray#218]
The cygwin feature seems more or less in tact other than the absence of getting a decent copy of cthelper. building it from the latest source tree against cygwin 32 and 64 works. Is there any reason it isn't being built currently?

**Comment by ttyusupov** [comment]
+1

**Comment by FauxFaux** [comment]
I'm dropping support for cygwin and adb, nobody seems to be using it anymore.
