### ISSUE TITLE
0.66-based release

### ISSUE THREAD

**Issue by vrutberg** [FauxFaux/PuTTYTray#225]
PuTTY versions prior to 0.66 includes a security vulnerability labeled vuln-ech-overflow.

It would be great to release a new version of PuTTY Tray based on PuTTY 0.66 which includes the fix for this security vulnerability.

More reading about vuln-ech-overflow: http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/vuln-ech-overflow.html

**Comment by FauxFaux** [comment]
Thanks for reminding me, done: p0.66-t027 is on the website: https://puttytray.goeswhere.com/#download

**Comment by vrutberg** [comment]
Great, thanks!
