### ISSUE TITLE
Assertion error in random_unref from Restart Session

### ISSUE THREAD

**Issue by nyuszika7h** [FauxFaux/PuTTYTray#226]
![Screenshot](https://i.imgur.com/o5Irgb3.png)

PuTTYTray p0.65-t025

**Details:** I was trying to restart or duplicate the session (I don't remember which) because I was having connection issues. I can't consistently reproduce this, though, it's the first time this happened.

**Comment by FauxFaux** [comment]
Thanks for reporting this.

I think this is just more evidence that PuTTY can't survive this mid-session "restart session".

This specific issue appears to be that an ssh session failed to reconnect, and at the same time (maybe?) another session had finished shutting down.  random_active > 0 is part of random_unref(), which manages refcounting and frees resources after all ssh sessions have gone away.

**Comment by FauxFaux** [comment]
I'm dropping support for the re-connection code, properly this time.
