### ISSUE TITLE
ecdsa support for keygen & pageant

### ISSUE THREAD

**Issue by MLWALK3R** [FauxFaux/PuTTYTray#227]
Please add ecdsa key generation to keygen and ecdsa key support to pageant.

**Comment by FauxFaux** [comment]
As I mentioned in #204, upstream have written code for this, but have decided not to release it.  This makes me nervous, and I am also not going to release it, unless anyone can explain why it's unreleased.  Maybe it's better to take this up with upstream?

I personally would also like this feature, but I do not feel like trying to discuss it with upstream.

The wishlist items now simply list them as having been fixed long ago, and available in development snapshots: http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/ecdsa.html

**Comment by cz-michi** [comment]
any updates? i think in development snapshot is correct code, am i wrong?
thanks, apperciate your work
