### ISSUE TITLE
adb connection via TCP/IP not possible when more then one device connected

### ISSUE THREAD

**Issue by hutorny** [FauxFaux/PuTTYTray#234]
Steps to reproduce:
1. Restart ADB on two phones in TCP/IP mode
       > adb tcpip 5555
2. Connect to both phones via TCP/IP
       > adb connect 192.168.0.100
       > adb connect 192.168.0.101
3. Ensure two devices are connected:
       > adb devices
       List of devices attached
       192.168.0.100:5555     device
       192.168.0.101:5555     device
4. Connecting with putty-adb "-a" expectingly fails with "more than one connected" error
5.  Enter 192.168.0.100:5555 in the putty-adb destination box and hit open

Expected result: putty-adb connects to the device
Actual result: putty-adb shows error message: "adb failure message 'device 192.168.0.100' not found"

**Comment by FauxFaux** [comment]
I'm dropping support for adb. Sorry.
