### ISSUE TITLE
Reconnect failure

### ISSUE THREAD

**Issue by devshans** [FauxFaux/PuTTYTray#236]
Running on Windows 10 with the newest build (v028), I have enabled the feature:

> "Connection" -> "Reconnect Options" -> "Attempt to reconnect on connection failure"

and

> "Session" -> "Close window on exit:" -> "Never"

When a connection is dropped, however, the terminal asserts that the connection was lost and it will try to reconnect. But the window the title bar shows (Inactive) and a connection attempt is not attempted without restarting the session.

This was working on version v021 - 25-Feb-2014 22:59 and confirmed on my system.

**Comment by FauxFaux** [comment]
I'm dropping support for the re-connection code, properly this time.
