### ISSUE TITLE
Rebuild against putty 0.67

### ISSUE THREAD

**Issue by tlundse** [FauxFaux/PuTTYTray#242]
These features are new in beta 0.67 (released 2016-03-05):

- Security fix: a buffer overrun in the old-style SCP protocol when receiving the header of each file downloaded from the server is fixed. See vuln-pscp-sink-sscanf.
- Windows PuTTY now sets its process ACL more restrictively, in an attempt to defend against malicious other processes reading sensitive data out of its memory.
- Assorted other robustness fixes for crashes and memory leaks.

**Comment by julianxhokaxhiu** [comment]
@FauxFaux please consider this

**Comment by ziesemer** [comment]
I realize this is a volunteer effort, but if there is anything that can be done to progress this - I and others would greatly appreciate it.  Unfortunately, it doesn't look like there have been any updates on this project for over 4 months now - hopefully not approaching abandonware.  If the current maintainer is no longer able to support this alone, maybe he could look to on-board others to remove himself as a the sole maintainer?  Or is it time for another fork?

Another PuTTY fork - KiTTY - was updated within 2 weeks of the 0.67 PuTTY release back in March.  I much prefer PuTTYTray over KiTTY - but if PuTTYTray isn't going to remain updated, I'll have to switch.

Also of consequence is https://github.com/FauxFaux/PuTTYTray#aims :

> PuTTY is a security product, and the security is critical. I want everyone, even very paranoid people, to be able to use PuTTYTray.

The PuTTY 0.67 release is documented as fixing a security hole (and other bugs).  As such, the current version of PuTTYTray can be considered as no longer being secure.

If PuTTYTray will no longer be updated, maybe KiTTY or another fork could take over some of the outstanding patches that are in PuTTYTray but not in their own forks.  (Ctrl+mousewheel zoom support is the most significant feature currently in PuTTYTray but missing in KiTTY for myself.)  Or even better, maybe another effort could be made at seeing if a number of the established, well-accepted features could be merged upstream?  At least PuTTY has a [documented team of 4 members](http://www.chiark.greenend.org.uk/~sgtatham/putty/team.html).  Also from https://github.com/FauxFaux/PuTTYTray#aims :

> There are a lot of patches against PuTTY that have never been submitted to, or have been rejected from, upstream. PuTTYTray is collecting these, with the aim of eventually getting them merged back in.

**Comment by FauxFaux** [comment]
The next release will, of course, be against 0.67. Sorry for the delay.
