### ISSUE TITLE
Code signing certificate has expired

### ISSUE THREAD

**Issue by pnegry** [FauxFaux/PuTTYTray#243]
Your certificate has expired (26/02/2016).

This is probably contributing to the smartscreen errors I get every time I try and start the app.

The fix would be to renew the certificate and resign the binary I guess?

**Comment by FauxFaux** [comment]
Recent (from the last year or so) binaries are timestamped, which is supposed to stop this from happening.  What smartscreen actually does inside is rather black box, though, unfortunately.

I will have a look.

**Comment by twpol** [comment]
The latest download, signed 24th Jan with certificate expired on 26 Feb 2016, was signed with SHA-2 but time-stamped with SHA-1 and thus considered invalid - SmartScreen requires the signature and time-stamp both be SHA-2 if the time-stamp is 1st Jan 2016 or later.

**Comment by pnegry** [comment]
Found this:

http://stackoverflow.com/questions/12311203/how-to-pass-the-smart-screen-on-win8-when-install-a-signed-application

which recommends using the WACK (Windows App Certification Kit)

**Comment by FauxFaux** [comment]
I've requested an updated certificate, but obviously it's not in a CA's interest to make my life easy by actually issuing it, or their life profitable by allowing me to pay them.  Sigh.
