### ISSUE TITLE
Reconnection problems

### ISSUE THREAD

**Issue by Ankkuli** [FauxFaux/PuTTYTray#244]
I cannot seem to be able to make any combination of the connection tabs settings so that it would actually work.

My case is this: I switch to different VPN and while doing that I have to disconnect, select a new VPN connection and connect. This doesn't go well with the PuttyTray, as it tries way too quickly to reconnect and since the VPN connection hasn't formed yet, it throws an error into my face. I tried to put all kinds of numbers to the "Seconds between keepalives" box and it didn't seem to make any difference. Likewise "Low-level TCP" boxes didn't change anything. "Reconnect options" made it TRY to reconnect but without once succeeding at that. Also I would like an option to disable the disconnection error popup. It's enough for me that the title says it has disconnected.

And might as well while I'm at it; how about adding [these two](http://i.imgur.com/eAzNXmb.png) little settings to the colours tab. I would really appreciate it.

Thanks anyway for the program, it's otherwise been great!

**Comment by FauxFaux** [comment]
I'm dropping support for the re-connection code, properly this time.
