### ISSUE TITLE
Puttytray silently dies if default configuration file comes from git repo

### ISSUE THREAD

**Issue by jleivo** [FauxFaux/PuTTYTray#247]
PuttyTray 0.66-t028 dies silently if using session files and the Default Settings file comes from GIT repo.
File that kills puttytray is [Default%2520Settings](https://dl.dropboxusercontent.com/u/131523/puttytray-git/Default%2520Settings)

**Comment by FauxFaux** [comment]
I've made the file parser aware that the file might have been corrupted by git (and silently fix the problem), and also made it crash noisily if there's a parse problem.
