### ISSUE TITLE
PuTTYTray windows can't be shared in Skype For Business.  Normal PuTTY works fine.

### ISSUE THREAD

**Issue by ziesemer** [FauxFaux/PuTTYTray#260]
When using Skype for Business, I cannot share a PuTTYTray window / app / program, without sharing the entire screen / display / monitor that it is on.  After using "Present" / "Present Programs..." from Skype FB, PuTTYTray simply does not appear in the list of programs that can be shared.  This happens whether at the saved sessions dialog, or for a connected session.  All of this works fine with the native PuTTY client.

I don't immediately see any differences between the PuTTY and PuTTYTray windows that would explain this.  I can operate on each window the same through Process Explorer, for example:  Selecting the process by using the window selector, as well as using the "Bring to Front", etc., commands.  I am also not running PuTTYTray as an elevated process, which would prevent this.

Windows 10.0.14393.  Skype for Business 2016 MSO (16.0.4432.1000) 64-bit.

**Comment by pnegry** [comment]
Process ACLs were loosened on the upstream putty, perhaps they are too tight on PuttyTray?

**Comment by ziesemer** [comment]
> Process ACLs were loosened on the upstream putty, perhaps they are too tight on PuttyTray?

That seems to be an understatement, and agreed.  Using Process Explorer against 0.67 versions (PuTTY and PuTTYTray ), I can't even view my own process details - running everything together as the same user.

This is fixed in PuTTY 0.68 (based on my testing).  It looks like the fix for this is https://github.com/FauxFaux/PuTTYTray/commit/e22120fea8d39e6a2ef6b2f4ab3ee5502f56169a.  See also: http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/win-process-acl-finesse.html

(Looks like my initial report here must have been with PuTTY 0.66 and PuTTYTray 0.67 - my bad.)

Anxiously awaiting the 0.68 rebuild (#264), for this and other concerns.  (Using native PuTTY in the meantime.)

**Comment by ziesemer** [comment]
Requires: #278.

**Comment by FauxFaux** [comment]
I'm just going to assume this will be fixed by the re-relaese, without testing it. Please feel free to re-open should a re-release happen, and it's still broken.
