### ISSUE TITLE
mkfiles.pl giving error message

### ISSUE THREAD

**Issue by epaulson10** [FauxFaux/PuTTYTray#266]
I am using Strawberry Perl 5.18.4 to try to generate the build files and I am getting this error:
Use of uninitialized value $dirfile in hash element at mkfiles.pl line 227.
Use of uninitialized value $dirfile in string at mkfiles.pl line 228.
unable to open source file be_all_u.m

A git bisect shows that this started occuring after commit [79079a81a70df](https://github.com/FauxFaux/PuTTYTray/commit/79079a81a70df975a2447761ffe9bb21f0d22f40).

**Comment by FauxFaux** [comment]
The `master` branch is currently a work in progress; please branch off one of the previous tags for now.
