### ISSUE TITLE
Is the project dead? (Not compatible with Windows 10 Creator 1703)

### ISSUE THREAD

**Issue by simvirus** [FauxFaux/PuTTYTray#277]
Dear team,
after the upgrade to Windows 10 Creator 1703 PuTTYTray can't work! :-(
The issue is *not* solved with the workaround from the ticket #269

> Nome dell'applicazione che ha generato l'errore: putty.exe, versione: 0.67.0.29, timestamp: 0x57711e67
> Nome del modulo che ha generato l'errore: unknown, versione: 0.0.0.0, timestamp: 0x00000000
> Codice eccezione: 0xc0000409
> Offset errore 0x54c0a020
> ID processo che ha generato l'errore: 0x200c
> Ora di avvio dell'applicazione che ha generato l'errore: 0x01d33f59534f2f0b
> Percorso dell'applicazione che ha generato l'errore: C:\Users\Win\Dropbox\Connections\Putty\putty.exe
> Percorso del modulo che ha generato l'errore: unknown
> ID segnalazione: 952cfccd-d432-411d-9764-97d69c2c5c5f
> Nome completo pacchetto che ha generato l'errore:
> ID applicazione relativo al pacchetto che ha generato l'errore: 1000

Which program we can use with the feature "Session from file" as PuTTYTray?

**Comment by JasonUnger** [comment]
I am using PuTTyTray fine here, and `ver` reports `Microsoft Windows [Version 10.0.15063]` for me.

**Comment by simvirus** [comment]
Sure, but as you can see after last update this is the output from event viewer.
The problem appeared only after the update.
Also my "ver" is "Microsoft Windows [Versione 10.0.15063]".
It may be a localized problem, for example "Windows language"... or other
Is there a command line or parameter to run with debug?
Thanks

**Comment by FauxFaux** [comment]
As others have said, this is not an issue that is affecting many people. It doesn't affect me.

PuTTYTray itself does not have any debugging inside.

Ideally, this needs to happen on a developer machine, and for a developer to attempt to diagnose it.

I still suspect that it's crappy security products, like anti-virus or firewalls, however.

Please continue the discussion on the original ticket.
