### ISSUE TITLE
Auto reconnect Delay

### ISSUE THREAD

**Issue by WiredWonder** [FauxFaux/PuTTYTray#28]
My machine takes 5 or so seconds to bring the NIC up when coming out of sleep.  As a result, the Auto reconnect function gives me a host not found error and aborts the connection, closing the window.

Two suggestions:
1.  Include a delay (or a retry for 5 seconds?)
2.  Leave the window open if the reconnect fails

**Comment by galapogos01** [comment]
Can this issue be reopened?  0.65-t026 has lost this delay widget meaning all my sessions won't reconnect on wake.  Please put it back!
