### ISSUE TITLE
"perl mkfiles.pl" doesn't work anymore?

### ISSUE THREAD

**Issue by zxpatric** [FauxFaux/PuTTYTray#280]
windows 10

C:\projects\PuTTYTray>git branch
* master

C:\projects\PuTTYTray>perl mkfiles.pl
Use of uninitialized value $dirfile in hash element at mkfiles.pl line 227.
Use of uninitialized value $dirfile in string at mkfiles.pl line 228.
unable to open source file be_all_u.m

C:\projects\PuTTYTray>perl --version

This is perl 5, version 26, subversion 1 (v5.26.1) built for MSWin32-x64-multi-thread

**Comment by zxpatric** [comment]
Try in Windows 7 with Strawberry Perl 5.18.4. Didn't work. So guess mkfiles.pl is broken. 

e:\projects\PuTTYTray>"d:\Bin\strawberry\perl\bin\perl.exe" mkfiles.pl
Use of uninitialized value $dirfile in hash element at mkfiles.pl line 227.
Use of uninitialized value $dirfile in string at mkfiles.pl line 228.
unable to open source file be_all_u.m

e:\projects\PuTTYTray>git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean

e:\projects\PuTTYTray>"d:\Bin\strawberry\perl\bin\perl.exe" --version

This is perl 5, version 18, subversion 4 (v5.18.4) built for MSWin32-x64-multi-thread

Copyright 1987-2013, Larry Wall

**Comment by bavis-m** [comment]
This is because regex_lib is built from a .cpp file, which mkfies.pl doesn't know how to import. Check out my  PR #281 to see how to fix this issue for yourself right away (with a one-liner)

**Comment by FauxFaux** [comment]
This is fixed by my new build system, which was totally not a waste of time.
