### ISSUE TITLE
Commit 16f019fee7 (url: merge a load of code from t67) creates many references to undefined variables in window.c

### ISSUE THREAD

**Issue by bavis-m** [FauxFaux/PuTTYTray#282]
The given commit adds a bunch of code that contains references to variables that don't exist.

The ones my VS2015 gives before giving up:

- `cursor_pt` in WndProc (easy to see you should add `POINT cursor_pt;`)
- `update_url_id`, `IDM_URL_MAX`, `IDM_URL_MIN`, `url_character_used`, `search_url_id`, `url_target_id`, which I can't figure out how to get going (seems to be partial text match to URLs in a menu?)
- `url_menu`, a new menu for selecting URLs from a dropdown?
- `urlhack_mouse_old_x`, `urlhack_mouse_old_y` selecting from the menu?

**Comment by FauxFaux** [comment]
Yes. It's a work in progress. All the branches are subject to my whims. Please work from tags, as it says in the README.
