### ISSUE TITLE
Documentation should describe how to use Sessions in File

### ISSUE THREAD

**Issue by jaraco** [FauxFaux/PuTTYTray#49]
Since the upstream documentation only describes sessions in the registry, it's not clear how Sessions in File works. The web site and wiki only currently list features. I was unable to find any documentation on how to use PuTTYTray-specific features.

Some things the documentation could cover:
- how to use sessions in file (used by default if no sessions, including Default, are defined in registry)
- where are sessions files stored
- how one can customize where session files are stored (if possible)
- how to migrate from registry-based sessions to file-based sessions

If someone would answer these questions here, I'll edit the wiki.

**Comment by anzz1** [comment]
Thanks for this, so for clarification when you want a portable installation, follow these steps:
1. Create a empty `putty.conf` file next to `putty.exe`
2. For "Default Settings" and each of the settings you might already have in the "Sessions from Registry" tab:
    - "Load" it, then change over to "Sessions from file" tab and "Save".
    - "Delete" it from the "Sessions from registry" tab.
3. Delete the `HKEY_CURRENT_USER\Software\SimonTatham\PuTTY` registry key for good measure.
4. Now all the settings will be saved in the PuTTY directory which you can take anywhere with you, and PuTTy will open to the "Sessions from file" tab by default, and registry will be untouched from now on.

**Comment by jaraco** [comment]
This is amazing. Thanks. I updated the File Behavior wiki page to include this guidance, which I'm sure would have served me well at the time.
