### ISSUE TITLE
Url clicking in scrollback buffer is failing

### ISSUE THREAD

**Issue by kouze** [FauxFaux/PuTTYTray#93]
When one clicks on an url in the scrollback buffer, putty is not "opening" the url you are clicking on, it opens "something else" instead.
Bug identified in some of the newest releases, not included in v013 for example.

**Comment by Phoenix09** [comment]
this is happening to me on 0.63-t022
steps I did to reproduce:
open SSH session
hold enter until it fills the screen
`$ echo http://google.com`
click link (the echoed one), opens as expected
scroll up one line
click link again, opens browser to part of my prompt the same length as the URL

**Comment by Phoenix09** [comment]
seriously? no response?
I can reproduce this on Windows 7, 8.1, and 10, on 4 different computers, one is a clean install of Windows 10

**Comment by FauxFaux** [comment]
Ah, I can actually reproduce this with Phoenix09's instructions.

**Comment by FauxFaux** [comment]
Let's see how that works for people!

**Comment by Phoenix09** [comment]
that works
thanks
