### ISSUE TITLE
Putty p0.63-t018 unable to authenticate when using SSH2-DSA key

### ISSUE THREAD

**Issue by bglover** [FauxFaux/PuTTYTray#94]
After successfully connecting to the server, I'm prompted for the pass phrase for my private key:
![ssh_login_prompt](https://f.cloud.github.com/assets/3111309/1030166/076f0868-0ead-11e3-9081-728cb3249d8d.png)

After entering the correct pass phrase, I'm presented with a "Microsoft Visual C++ Runtime Library" error dialog:
![putty_error_dialog](https://f.cloud.github.com/assets/3111309/1030172/1b15468e-0ead-11e3-8b92-caea0f52814f.png)
### Notes
1. Pressing either "Abort" button or "Retry" button terminates the application.
2. Pressing the "Ignore" button will allow the authentication to continue.
3. Pressing enter at the pass phrase prompt or entering the wrong pass phrase does not trigger the warning but, as expected, re-prompts for my pass phrase.
4. The error is not triggered when using SSH2-RSA keys.
5. Bit length doesn't matter (I tried 1024, 2048 and 4096)
6. Using a SSH2-DSA key _without_ a pass phrase also triggers the error.

**Comment by ankurkasliwal** [comment]
I am seeing same issue wit putty, how can i fix this
