### ISSUE TITLE
Crash when importing old key

### ISSUE THREAD

**Issue by ghost** [FauxFaux/PuTTYTray#95]
When I import my ancient key I get this:
File: ..\sshdss.c
Line: 430

Expression: hash

![image](https://f.cloud.github.com/assets/1162544/1031598/d3620a04-0ee6-11e3-84b9-8d965aefbf9e.png)

**Comment by ankurkasliwal** [comment]
@FauxFaux : I am seeing same issue but not able to fix this. Putty was working fine few days back but I started seeing this issue after i did saved a session of putty.

Now i see an IP address alwats gets populated in my hostname section when i start putty. If i press ignore console comes up fine but if i do full screen putty crashes.
